
// Generated by Cadence Genus(TM) Synthesis Solution 20.10-p001_1
// Generated on: May 17 2023 17:30:49 IST (May 17 2023 12:00:49 UTC)

// Verification Directory fv/mem_always_on 

module mem_always_on(rx_cmd, packet_complete, tx_enable,
     ADC_data_ready, clk, factory_reset, current_inven_flag_in,
     current_sl_flag_in, Code1_in, Counter_EPC_in, Counter_s1_in,
     Counter_s2_in, Counter_EPC_out, Counter_s1_out, Counter_s2_out,
     current_inven_flag_out, current_sl_flag_out, Code1_out);
  input [13:0] rx_cmd;
  input packet_complete, tx_enable, ADC_data_ready, clk, factory_reset,
       current_inven_flag_in, current_sl_flag_in;
  input [15:0] Code1_in;
  input [5:0] Counter_EPC_in, Counter_s1_in, Counter_s2_in;
  output [5:0] Counter_EPC_out, Counter_s1_out, Counter_s2_out;
  output current_inven_flag_out, current_sl_flag_out;
  output [15:0] Code1_out;
  wire [13:0] rx_cmd;
  wire packet_complete, tx_enable, ADC_data_ready, clk, factory_reset,
       current_inven_flag_in, current_sl_flag_in;
  wire [15:0] Code1_in;
  wire [5:0] Counter_EPC_in, Counter_s1_in, Counter_s2_in;
  wire [5:0] Counter_EPC_out, Counter_s1_out, Counter_s2_out;
  wire current_inven_flag_out, current_sl_flag_out;
  wire [15:0] Code1_out;
  wire [15:0] Code1;
  wire [5:0] Counter_s2;
  wire [5:0] Counter_s1;
  wire [5:0] Counter_EPC;
  wire current_inven_flag, current_sl_flag, in_flag, n_0, n_1, n_2,
       n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89;
  DFQD1BWP7T \Code1_out_reg[0] (.CP (clk), .D (n_89), .Q
       (Code1_out[0]));
  DFQD1BWP7T \Code1_out_reg[3] (.CP (clk), .D (n_72), .Q
       (Code1_out[3]));
  DFQD1BWP7T \Code1_out_reg[4] (.CP (clk), .D (n_82), .Q
       (Code1_out[4]));
  DFQD1BWP7T \Code1_out_reg[5] (.CP (clk), .D (n_80), .Q
       (Code1_out[5]));
  DFQD1BWP7T \Code1_out_reg[6] (.CP (clk), .D (n_74), .Q
       (Code1_out[6]));
  DFQD1BWP7T \Code1_out_reg[7] (.CP (clk), .D (n_75), .Q
       (Code1_out[7]));
  DFQD1BWP7T \Code1_out_reg[8] (.CP (clk), .D (n_83), .Q
       (Code1_out[8]));
  DFQD1BWP7T \Code1_out_reg[9] (.CP (clk), .D (n_77), .Q
       (Code1_out[9]));
  DFQD1BWP7T \Code1_out_reg[10] (.CP (clk), .D (n_73), .Q
       (Code1_out[10]));
  DFQD1BWP7T \Code1_out_reg[11] (.CP (clk), .D (n_76), .Q
       (Code1_out[11]));
  DFQD1BWP7T \Code1_out_reg[12] (.CP (clk), .D (n_79), .Q
       (Code1_out[12]));
  DFQD1BWP7T \Code1_out_reg[1] (.CP (clk), .D (n_81), .Q
       (Code1_out[1]));
  DFQD1BWP7T \Code1_out_reg[13] (.CP (clk), .D (n_88), .Q
       (Code1_out[13]));
  DFQD1BWP7T \Code1_out_reg[14] (.CP (clk), .D (n_84), .Q
       (Code1_out[14]));
  DFQD1BWP7T \Code1_out_reg[15] (.CP (clk), .D (n_71), .Q
       (Code1_out[15]));
  DFQD1BWP7T \Code1_out_reg[2] (.CP (clk), .D (n_78), .Q
       (Code1_out[2]));
  AO222D0BWP7T g3418(.A1 (n_87), .A2 (Code1[0]), .B1 (n_86), .B2
       (Code1_in[0]), .C1 (Code1_out[0]), .C2 (n_85), .Z (n_89));
  AO222D0BWP7T g3413(.A1 (n_87), .A2 (Code1[13]), .B1 (n_86), .B2
       (Code1_in[13]), .C1 (Code1_out[13]), .C2 (n_85), .Z (n_88));
  AO222D0BWP7T g3414(.A1 (n_87), .A2 (Code1[14]), .B1 (n_86), .B2
       (Code1_in[14]), .C1 (Code1_out[14]), .C2 (n_85), .Z (n_84));
  AO222D0BWP7T g3404(.A1 (n_87), .A2 (Code1[8]), .B1 (n_86), .B2
       (Code1_in[8]), .C1 (Code1_out[8]), .C2 (n_85), .Z (n_83));
  AO222D0BWP7T g3408(.A1 (n_87), .A2 (Code1[4]), .B1 (n_86), .B2
       (Code1_in[4]), .C1 (Code1_out[4]), .C2 (n_85), .Z (n_82));
  AO222D0BWP7T g3415(.A1 (n_87), .A2 (Code1[1]), .B1 (n_86), .B2
       (Code1_in[1]), .C1 (Code1_out[1]), .C2 (n_85), .Z (n_81));
  AO222D0BWP7T g3405(.A1 (n_87), .A2 (Code1[5]), .B1 (n_86), .B2
       (Code1_in[5]), .C1 (Code1_out[5]), .C2 (n_85), .Z (n_80));
  AO222D0BWP7T g3416(.A1 (n_87), .A2 (Code1[12]), .B1 (n_86), .B2
       (Code1_in[12]), .C1 (Code1_out[12]), .C2 (n_85), .Z (n_79));
  AO222D0BWP7T g3417(.A1 (n_87), .A2 (Code1[2]), .B1 (n_86), .B2
       (Code1_in[2]), .C1 (Code1_out[2]), .C2 (n_85), .Z (n_78));
  AO222D0BWP7T g3409(.A1 (n_87), .A2 (Code1[9]), .B1 (n_86), .B2
       (Code1_in[9]), .C1 (Code1_out[9]), .C2 (n_85), .Z (n_77));
  AO222D0BWP7T g3411(.A1 (n_87), .A2 (Code1[11]), .B1 (n_86), .B2
       (Code1_in[11]), .C1 (Code1_out[11]), .C2 (n_85), .Z (n_76));
  AO222D0BWP7T g3407(.A1 (n_87), .A2 (Code1[7]), .B1 (n_86), .B2
       (Code1_in[7]), .C1 (Code1_out[7]), .C2 (n_85), .Z (n_75));
  AO222D0BWP7T g3406(.A1 (n_87), .A2 (Code1[6]), .B1 (n_86), .B2
       (Code1_in[6]), .C1 (Code1_out[6]), .C2 (n_85), .Z (n_74));
  AO222D0BWP7T g3410(.A1 (n_87), .A2 (Code1[10]), .B1 (n_86), .B2
       (Code1_in[10]), .C1 (Code1_out[10]), .C2 (n_85), .Z (n_73));
  AO222D0BWP7T g3419(.A1 (n_87), .A2 (Code1[3]), .B1 (n_86), .B2
       (Code1_in[3]), .C1 (Code1_out[3]), .C2 (n_85), .Z (n_72));
  DFQD1BWP7T \Counter_s2_out_reg[5] (.CP (clk), .D (n_52), .Q
       (Counter_s2_out[5]));
  DFQD1BWP7T \Code1_reg[0] (.CP (clk), .D (n_44), .Q (Code1[0]));
  DFQD1BWP7T \Code1_reg[9] (.CP (clk), .D (n_60), .Q (Code1[9]));
  DFQD1BWP7T \Code1_reg[11] (.CP (clk), .D (n_51), .Q (Code1[11]));
  DFQD1BWP7T \Code1_reg[12] (.CP (clk), .D (n_48), .Q (Code1[12]));
  DFQD1BWP7T \Code1_reg[13] (.CP (clk), .D (n_47), .Q (Code1[13]));
  DFQD1BWP7T \Counter_s2_out_reg[3] (.CP (clk), .D (n_54), .Q
       (Counter_s2_out[3]));
  AO222D0BWP7T g3412(.A1 (n_87), .A2 (Code1[15]), .B1 (n_86), .B2
       (Code1_in[15]), .C1 (Code1_out[15]), .C2 (n_85), .Z (n_71));
  DFQD1BWP7T \Code1_reg[15] (.CP (clk), .D (n_45), .Q (Code1[15]));
  DFQD1BWP7T \Counter_s1_out_reg[0] (.CP (clk), .D (n_70), .Q
       (Counter_s1_out[0]));
  DFQD1BWP7T \Counter_s1_out_reg[1] (.CP (clk), .D (n_64), .Q
       (Counter_s1_out[1]));
  DFQD1BWP7T \Counter_s1_out_reg[2] (.CP (clk), .D (n_63), .Q
       (Counter_s1_out[2]));
  DFQD1BWP7T \Counter_s1_out_reg[3] (.CP (clk), .D (n_62), .Q
       (Counter_s1_out[3]));
  DFQD1BWP7T \Counter_s1_out_reg[4] (.CP (clk), .D (n_61), .Q
       (Counter_s1_out[4]));
  DFQD1BWP7T \Counter_s1_out_reg[5] (.CP (clk), .D (n_68), .Q
       (Counter_s1_out[5]));
  DFQD1BWP7T \Counter_s2_out_reg[0] (.CP (clk), .D (n_57), .Q
       (Counter_s2_out[0]));
  DFQD1BWP7T \Code1_reg[10] (.CP (clk), .D (n_69), .Q (Code1[10]));
  DFQD1BWP7T \Code1_reg[1] (.CP (clk), .D (n_43), .Q (Code1[1]));
  DFQD1BWP7T \Code1_reg[14] (.CP (clk), .D (n_46), .Q (Code1[14]));
  DFQD1BWP7T \Code1_reg[2] (.CP (clk), .D (n_42), .Q (Code1[2]));
  DFQD1BWP7T \Code1_reg[3] (.CP (clk), .D (n_41), .Q (Code1[3]));
  DFQD1BWP7T \Counter_s2_out_reg[4] (.CP (clk), .D (n_53), .Q
       (Counter_s2_out[4]));
  DFQD1BWP7T \Code1_reg[4] (.CP (clk), .D (n_39), .Q (Code1[4]));
  DFQD1BWP7T \Counter_s2_out_reg[2] (.CP (clk), .D (n_55), .Q
       (Counter_s2_out[2]));
  DFQD1BWP7T \Code1_reg[5] (.CP (clk), .D (n_36), .Q (Code1[5]));
  DFQD1BWP7T \Code1_reg[6] (.CP (clk), .D (n_37), .Q (Code1[6]));
  DFQD1BWP7T \Code1_reg[7] (.CP (clk), .D (n_38), .Q (Code1[7]));
  DFQD1BWP7T \Code1_reg[8] (.CP (clk), .D (n_40), .Q (Code1[8]));
  DFQD1BWP7T \Counter_s2_out_reg[1] (.CP (clk), .D (n_56), .Q
       (Counter_s2_out[1]));
  DFQD1BWP7T \Counter_s2_reg[3] (.CP (clk), .D (n_31), .Q
       (Counter_s2[3]));
  DFQD1BWP7T \Counter_s1_reg[4] (.CP (clk), .D (n_27), .Q
       (Counter_s1[4]));
  DFQD1BWP7T \Counter_s2_reg[0] (.CP (clk), .D (n_23), .Q
       (Counter_s2[0]));
  DFQD1BWP7T \Counter_s1_reg[1] (.CP (clk), .D (n_30), .Q
       (Counter_s1[1]));
  DFQD1BWP7T \Counter_s1_reg[2] (.CP (clk), .D (n_29), .Q
       (Counter_s1[2]));
  DFQD1BWP7T \Counter_s1_reg[3] (.CP (clk), .D (n_22), .Q
       (Counter_s1[3]));
  DFQD1BWP7T \Counter_s1_reg[5] (.CP (clk), .D (n_26), .Q
       (Counter_s1[5]));
  DFQD1BWP7T \Counter_s1_reg[0] (.CP (clk), .D (n_35), .Q
       (Counter_s1[0]));
  DFQD1BWP7T \Counter_s2_reg[4] (.CP (clk), .D (n_28), .Q
       (Counter_s2[4]));
  DFQD1BWP7T \Counter_s2_reg[2] (.CP (clk), .D (n_34), .Q
       (Counter_s2[2]));
  DFQD1BWP7T \Counter_s2_reg[5] (.CP (clk), .D (n_24), .Q
       (Counter_s2[5]));
  DFQD1BWP7T \Counter_s2_reg[1] (.CP (clk), .D (n_25), .Q
       (Counter_s2[1]));
  AO222D0BWP7T g3453(.A1 (n_67), .A2 (Counter_s1[0]), .B1
       (Counter_s1_out[0]), .B2 (n_66), .C1 (n_65), .C2
       (Counter_s1_in[0]), .Z (n_70));
  AO22D0BWP7T g3481(.A1 (n_59), .A2 (Code1_in[10]), .B1 (n_58), .B2
       (Code1[10]), .Z (n_69));
  AO222D0BWP7T g3448(.A1 (n_67), .A2 (Counter_s1[5]), .B1
       (Counter_s1_out[5]), .B2 (n_66), .C1 (n_65), .C2
       (Counter_s1_in[5]), .Z (n_68));
  AO222D0BWP7T g3449(.A1 (n_67), .A2 (Counter_s1[1]), .B1
       (Counter_s1_out[1]), .B2 (n_66), .C1 (n_65), .C2
       (Counter_s1_in[1]), .Z (n_64));
  AO222D0BWP7T g3450(.A1 (n_67), .A2 (Counter_s1[2]), .B1
       (Counter_s1_out[2]), .B2 (n_66), .C1 (n_65), .C2
       (Counter_s1_in[2]), .Z (n_63));
  AO222D0BWP7T g3451(.A1 (n_67), .A2 (Counter_s1[3]), .B1
       (Counter_s1_out[3]), .B2 (n_66), .C1 (n_65), .C2
       (Counter_s1_in[3]), .Z (n_62));
  AO222D0BWP7T g3452(.A1 (n_67), .A2 (Counter_s1[4]), .B1
       (Counter_s1_out[4]), .B2 (n_66), .C1 (n_65), .C2
       (Counter_s1_in[4]), .Z (n_61));
  AO22D0BWP7T g3480(.A1 (n_59), .A2 (Code1_in[9]), .B1 (n_58), .B2
       (Code1[9]), .Z (n_60));
  AO222D0BWP7T g3454(.A1 (n_67), .A2 (Counter_s2[0]), .B1
       (Counter_s2_out[0]), .B2 (n_66), .C1 (n_65), .C2
       (Counter_s2_in[0]), .Z (n_57));
  AO222D0BWP7T g3455(.A1 (n_67), .A2 (Counter_s2[1]), .B1 (n_65), .B2
       (Counter_s2_in[1]), .C1 (Counter_s2_out[1]), .C2 (n_66), .Z
       (n_56));
  AO222D0BWP7T g3456(.A1 (n_67), .A2 (Counter_s2[2]), .B1
       (Counter_s2_out[2]), .B2 (n_66), .C1 (n_65), .C2
       (Counter_s2_in[2]), .Z (n_55));
  AO222D0BWP7T g3457(.A1 (n_67), .A2 (Counter_s2[3]), .B1
       (Counter_s2_out[3]), .B2 (n_66), .C1 (n_65), .C2
       (Counter_s2_in[3]), .Z (n_54));
  AO222D0BWP7T g3458(.A1 (n_67), .A2 (Counter_s2[4]), .B1 (n_65), .B2
       (Counter_s2_in[4]), .C1 (Counter_s2_out[4]), .C2 (n_66), .Z
       (n_53));
  AO222D0BWP7T g3465(.A1 (n_67), .A2 (Counter_s2[5]), .B1 (n_65), .B2
       (Counter_s2_in[5]), .C1 (Counter_s2_out[5]), .C2 (n_66), .Z
       (n_52));
  AO22D0BWP7T g3466(.A1 (n_59), .A2 (Code1_in[11]), .B1 (n_58), .B2
       (Code1[11]), .Z (n_51));
  EDFKCNQD1BWP7T \Counter_EPC_reg[1] (.CP (clk), .CN (n_50), .D
       (Counter_EPC_in[1]), .E (n_49), .Q (Counter_EPC[1]));
  EDFKCNQD1BWP7T \Counter_EPC_reg[3] (.CP (clk), .CN (n_50), .D
       (Counter_EPC_in[3]), .E (n_49), .Q (Counter_EPC[3]));
  AO22D0BWP7T g3467(.A1 (n_59), .A2 (Code1_in[12]), .B1 (n_58), .B2
       (Code1[12]), .Z (n_48));
  AO22D0BWP7T g3468(.A1 (n_59), .A2 (Code1_in[13]), .B1 (n_58), .B2
       (Code1[13]), .Z (n_47));
  AO22D0BWP7T g3469(.A1 (n_59), .A2 (Code1_in[14]), .B1 (n_58), .B2
       (Code1[14]), .Z (n_46));
  AO22D0BWP7T g3470(.A1 (n_59), .A2 (Code1_in[15]), .B1 (n_58), .B2
       (Code1[15]), .Z (n_45));
  AO22D0BWP7T g3471(.A1 (n_59), .A2 (Code1_in[0]), .B1 (n_58), .B2
       (Code1[0]), .Z (n_44));
  AO22D0BWP7T g3472(.A1 (n_59), .A2 (Code1_in[1]), .B1 (n_58), .B2
       (Code1[1]), .Z (n_43));
  AO22D0BWP7T g3473(.A1 (n_59), .A2 (Code1_in[2]), .B1 (n_58), .B2
       (Code1[2]), .Z (n_42));
  AO22D0BWP7T g3474(.A1 (n_59), .A2 (Code1_in[3]), .B1 (n_58), .B2
       (Code1[3]), .Z (n_41));
  AO22D0BWP7T g3479(.A1 (n_59), .A2 (Code1_in[8]), .B1 (n_58), .B2
       (Code1[8]), .Z (n_40));
  AO22D0BWP7T g3475(.A1 (n_59), .A2 (Code1_in[4]), .B1 (n_58), .B2
       (Code1[4]), .Z (n_39));
  AO22D0BWP7T g3478(.A1 (n_59), .A2 (Code1_in[7]), .B1 (n_58), .B2
       (Code1[7]), .Z (n_38));
  AO22D0BWP7T g3477(.A1 (n_59), .A2 (Code1_in[6]), .B1 (n_58), .B2
       (Code1[6]), .Z (n_37));
  AO22D0BWP7T g3476(.A1 (n_59), .A2 (Code1_in[5]), .B1 (n_58), .B2
       (Code1[5]), .Z (n_36));
  EDFKCNQD1BWP7T \Counter_EPC_reg[5] (.CP (clk), .CN (n_50), .D
       (Counter_EPC_in[5]), .E (n_49), .Q (Counter_EPC[5]));
  EDFKCNQD1BWP7T \Counter_EPC_reg[0] (.CP (clk), .CN (n_50), .D
       (Counter_EPC_in[0]), .E (n_49), .Q (Counter_EPC[0]));
  EDFKCNQD1BWP7T \Counter_EPC_reg[2] (.CP (clk), .CN (n_50), .D
       (Counter_EPC_in[2]), .E (n_49), .Q (Counter_EPC[2]));
  EDFKCNQD1BWP7T \Counter_EPC_reg[4] (.CP (clk), .CN (n_50), .D
       (Counter_EPC_in[4]), .E (n_49), .Q (Counter_EPC[4]));
  AO22D0BWP7T g3508(.A1 (n_33), .A2 (Counter_s1[0]), .B1 (n_32), .B2
       (Counter_s1_in[0]), .Z (n_35));
  AO22D0BWP7T g3499(.A1 (n_33), .A2 (Counter_s2[2]), .B1 (n_32), .B2
       (Counter_s2_in[2]), .Z (n_34));
  AO22D0BWP7T g3498(.A1 (n_33), .A2 (Counter_s2[3]), .B1 (n_32), .B2
       (Counter_s2_in[3]), .Z (n_31));
  AO22D0BWP7T g3509(.A1 (n_33), .A2 (Counter_s1[1]), .B1 (n_32), .B2
       (Counter_s1_in[1]), .Z (n_30));
  AO22D0BWP7T g3510(.A1 (n_33), .A2 (Counter_s1[2]), .B1 (n_32), .B2
       (Counter_s1_in[2]), .Z (n_29));
  NR2D1BWP7T g3494(.A1 (n_20), .A2 (n_21), .ZN (n_87));
  AO22D0BWP7T g3517(.A1 (n_33), .A2 (Counter_s2[4]), .B1 (n_32), .B2
       (Counter_s2_in[4]), .Z (n_28));
  AO22D0BWP7T g3512(.A1 (n_33), .A2 (Counter_s1[4]), .B1 (n_32), .B2
       (Counter_s1_in[4]), .Z (n_27));
  AO22D0BWP7T g3513(.A1 (n_33), .A2 (Counter_s1[5]), .B1 (n_32), .B2
       (Counter_s1_in[5]), .Z (n_26));
  AO22D0BWP7T g3514(.A1 (n_33), .A2 (Counter_s2[1]), .B1 (n_32), .B2
       (Counter_s2_in[1]), .Z (n_25));
  AO22D0BWP7T g3515(.A1 (n_33), .A2 (Counter_s2[5]), .B1 (n_32), .B2
       (Counter_s2_in[5]), .Z (n_24));
  AO22D0BWP7T g3516(.A1 (n_33), .A2 (Counter_s2[0]), .B1 (n_32), .B2
       (Counter_s2_in[0]), .Z (n_23));
  AO22D0BWP7T g3511(.A1 (n_33), .A2 (Counter_s1[3]), .B1 (n_32), .B2
       (Counter_s1_in[3]), .Z (n_22));
  NR2XD0BWP7T g3495(.A1 (n_18), .A2 (n_21), .ZN (n_86));
  DFQD1BWP7T current_inven_flag_out_reg(.CP (clk), .D (n_16), .Q
       (current_inven_flag_out));
  DFQD1BWP7T current_sl_flag_out_reg(.CP (clk), .D (n_15), .Q
       (current_sl_flag_out));
  EDFKCNQD1BWP7T \Counter_EPC_out_reg[2] (.CP (clk), .CN (n_50), .D
       (Counter_EPC[2]), .E (n_19), .Q (Counter_EPC_out[2]));
  DFKCNQD1BWP7T in_flag_reg(.CP (clk), .CN (n_50), .D (n_6), .Q
       (in_flag));
  INVD0BWP7T g3496(.I (n_58), .ZN (n_20));
  EDFKCNQD1BWP7T \Counter_EPC_out_reg[4] (.CP (clk), .CN (n_50), .D
       (Counter_EPC[4]), .E (n_19), .Q (Counter_EPC_out[4]));
  CKND1BWP7T g3497(.I (n_18), .ZN (n_59));
  EDFKCNQD1BWP7T \Counter_EPC_out_reg[5] (.CP (clk), .CN (n_50), .D
       (Counter_EPC[5]), .E (n_19), .Q (Counter_EPC_out[5]));
  EDFKCNQD1BWP7T \Counter_EPC_out_reg[3] (.CP (clk), .CN (n_50), .D
       (Counter_EPC[3]), .E (n_19), .Q (Counter_EPC_out[3]));
  EDFKCNQD1BWP7T \Counter_EPC_out_reg[0] (.CP (clk), .CN (n_50), .D
       (Counter_EPC[0]), .E (n_19), .Q (Counter_EPC_out[0]));
  EDFKCNQD1BWP7T \Counter_EPC_out_reg[1] (.CP (clk), .CN (n_50), .D
       (Counter_EPC[1]), .E (n_19), .Q (Counter_EPC_out[1]));
  DFQD1BWP7T current_inven_flag_reg(.CP (clk), .D (n_9), .Q
       (current_inven_flag));
  DFQD1BWP7T current_sl_flag_reg(.CP (clk), .D (n_11), .Q
       (current_sl_flag));
  ND2D0BWP7T g3507(.A1 (n_17), .A2 (n_50), .ZN (n_18));
  NR3D0BWP7T g3524(.A1 (n_12), .A2 (n_10), .A3 (factory_reset), .ZN
       (n_67));
  NR2D1BWP7T g3526(.A1 (n_13), .A2 (factory_reset), .ZN (n_32));
  NR2XD0BWP7T g3506(.A1 (n_17), .A2 (factory_reset), .ZN (n_58));
  AO221D0BWP7T g3529(.A1 (current_inven_flag), .A2 (n_14), .B1
       (current_inven_flag_out), .B2 (n_21), .C (factory_reset), .Z
       (n_16));
  AO221D0BWP7T g3532(.A1 (current_sl_flag), .A2 (n_14), .B1
       (current_sl_flag_out), .B2 (n_21), .C (factory_reset), .Z
       (n_15));
  CKAN2D1BWP7T g3527(.A1 (n_13), .A2 (n_50), .Z (n_33));
  AN2D1BWP7T g3528(.A1 (n_12), .A2 (n_50), .Z (n_65));
  AO221D0BWP7T g3531(.A1 (n_8), .A2 (current_sl_flag_in), .B1
       (current_sl_flag), .B2 (n_7), .C (factory_reset), .Z (n_11));
  AN2D1BWP7T g3525(.A1 (n_10), .A2 (n_50), .Z (n_66));
  AO221D0BWP7T g3530(.A1 (n_8), .A2 (current_inven_flag_in), .B1
       (current_inven_flag), .B2 (n_7), .C (factory_reset), .Z (n_9));
  OA21D0BWP7T g3533(.A1 (n_5), .A2 (n_1), .B (rx_cmd[8]), .Z (n_49));
  NR4D0BWP7T g3522(.A1 (n_0), .A2 (Counter_EPC[5]), .A3
       (Counter_EPC[4]), .A4 (Counter_EPC[3]), .ZN (n_17));
  INR2D1BWP7T g3536(.A1 (n_4), .B1 (n_3), .ZN (n_12));
  INR2D1BWP7T g3534(.A1 (n_5), .B1 (rx_cmd[8]), .ZN (n_6));
  AOI31D0BWP7T g3537(.A1 (packet_complete), .A2 (rx_cmd[10]), .A3
       (ADC_data_ready), .B (n_4), .ZN (n_13));
  NR2D1BWP7T g3540(.A1 (n_14), .A2 (factory_reset), .ZN (n_85));
  INR2D1BWP7T g3535(.A1 (n_3), .B1 (rx_cmd[11]), .ZN (n_10));
  NR2D1BWP7T g3538(.A1 (n_2), .A2 (tx_enable), .ZN (n_4));
  INR2D1BWP7T g3539(.A1 (tx_enable), .B1 (n_2), .ZN (n_5));
  INVD1BWP7T g3546(.I (n_21), .ZN (n_14));
  AO21D0BWP7T g3543(.A1 (n_1), .A2 (rx_cmd[8]), .B (rx_cmd[1]), .Z
       (n_19));
  IND3D1BWP7T g3541(.A1 (Counter_EPC[2]), .B1 (Counter_EPC[1]), .B2
       (Counter_EPC[0]), .ZN (n_0));
  INVD0BWP7T g3544(.I (n_7), .ZN (n_8));
  IND3D1BWP7T g3542(.A1 (ADC_data_ready), .B1 (rx_cmd[10]), .B2
       (packet_complete), .ZN (n_3));
  ND2D1BWP7T g3548(.A1 (n_1), .A2 (rx_cmd[4]), .ZN (n_21));
  ND2D1BWP7T g3545(.A1 (rx_cmd[4]), .A2 (packet_complete), .ZN (n_7));
  NR2XD0BWP7T g3547(.A1 (in_flag), .A2 (rx_cmd[11]), .ZN (n_2));
  INVD1BWP7T g3549(.I (packet_complete), .ZN (n_1));
  INVD1BWP7T g3550(.I (factory_reset), .ZN (n_50));
endmodule
